#기초 선형대수학

자료형 중 - 수칼라, 벡터, 행렬, 텐서(tensor)

- 스칼라(scalar) $x$ 1차원 
 1. 단순한 숫자
 2. 방향성이 없음
 3. 크기만 존재함
 4. 랭크가 0인 텐서

In [ ]:
import numpy as np

In [ ]:
#스칼라 예시
a = np.array(5) #수의 배열을 통칭함
print('값',a)
print('형태',a.shape)

값 5
형태 ()


- 벡터 $X$, n차원
 1. 숫자들의 배열
 2. 크기와 방향의 개념이 존재하는 수
 3. 예시) 속도 
 4. 랭크 1텐서

In [ ]:
#1차원
vec1 = np.array([5])
print('값',vec1)
print('형태',vec1.shape)

값 [5]
형태 (1,)


In [ ]:
# 1> 차원
vec2 = np.array([2,4])
print('값',vec2)
print('형태',vec2.shape)

vec3 = np.array([1,3,5])
print('값',vec3)
print('형태',vec3.shape)

vec5 = np.array([4,2,7,5,3])
print('값',vec5)
print('형태',vec5.shape)

값 [2 4]
형태 (2,)
값 [1 3 5]
형태 (3,)
값 [4 2 7 5 3]
형태 (5,)


- 행렬 $X$ , m*n차원 
 1. 수의 배열
 2. 벡터와 벡터끼리의 연관성 이해
 3. 선형방정식의 뿌리
 4. 예시)소와 닭이 합해서 8마리, 동물의 다리 개수가 26개일때 각각 몇마리?
 5. 랭크 2 텐서

In [ ]:
# 2x2 정방행렬
mat1 = np.array([[1,1],[4,2]])
print('값',mat1)
print('형태',mat1.shape)
# 4x3 행렬
mat2 = np.array([[1,1,2],[4,2,1],[3,7,4],[4,8,7]])
print('값',mat2)
print('형태',mat2.shape)

값 [[1 1]
 [4 2]]
형태 (2, 2)
값 [[1 1 2]
 [4 2 1]
 [3 7 4]
 [4 8 7]]
형태 (4, 3)


- 텐서
 1. 여기부터 어렵대여
 2. 다중선형사상
 3. 벡터가 쌓이는 것 = 랭크의 추가


_________________
- 텐서의 기초연산
 1. 덧셈
 2. 곱셈
   - 행렬 곱셈
   - 원소별 곱셈

In [ ]:
#덧셈 => 같은 형태의 텐서끼리만 덧셈 가능
A = np.array([3,5,6])
B = np.array([-1,2,0])
print(A+B)

[2 7 6]


In [ ]:
print(A-B)
B *= -1
print(A+B)

[4 3 6]
[4 3 6]


In [ ]:
A_1 = np.array([3,5,6])
A_2 = np.array([3,5,6,0])
print(A_1+A_2)   # => 차원이 다른 두 텐서(벡터)는 연산할 수 없음

ValueError: ignored

In [ ]:
# 행렬 곱셈 => 앞텐서의 마지막 차원, 뒷텐서의 첫번째차원이 같아야 계산 가능
A = np.random.normal(size=(5,3))
B = np.random.normal(size=(3,6))
print(A.shape)
print(B.shape)
C = np.matmul(A,B)
print(C.shape)

(5, 3)
(3, 6)
(5, 6)


In [ ]:
#과제
A_1 = np.random.normal(size=(10,5,3))
B_1 = np.random.normal(size=(3,20))
C_1 = np.matmul(A_1,B_1)
print(C_1.shape)
print(C_1)

(10, 5, 20)
[[[-2.05658984e-01 -1.81523673e+00  2.45696390e+00  1.58360742e+00
   -1.57780699e+00  4.27461341e-01 -2.94216528e+00 -1.56909329e+00
    8.89889488e-02  3.29741135e+00 -3.37254919e+00 -8.87521630e-02
   -1.08281644e+00  2.10089028e+00 -4.11238678e+00 -9.34801018e-01
    2.44765231e-01  2.60834270e+00 -2.76829279e+00 -2.70815595e+00]
  [-4.97420208e-01  1.75273409e+00 -1.90491743e+00 -3.22808660e+00
    7.40195328e-01 -1.66613956e+00  1.31700804e+00  8.66442535e-01
    1.13449782e-01  2.13548281e+00  3.39909529e+00 -1.15344144e+00
   -1.07440321e+00 -2.75701411e+00 -7.96031457e-01 -1.98137183e-01
    2.03960387e+00 -1.34649345e+00  1.07397697e+00  9.23211274e-01]
  [ 1.99623678e+00 -1.87728508e+00  2.76401322e+00  6.84476126e-01
   -3.07088918e+00  3.99553201e-01 -3.24614489e+00 -1.99002412e+00
    2.12679750e+00  3.50481896e+00 -2.29009904e+00 -5.67881754e-01
   -1.51982997e+00  2.31263723e+00 -4.49487515e+00  5.72732504e-01
    1.58195374e-01  2.87406550e+00 -2.17906108e+

In [ ]:
# 원소의 곱셈 => 두 텐서의 형태가 동일할 때 가능한 곱셈
A = np.array([[1,3,5],[2,4,8]])
B = np.array([[-1,0,3],[5,6,-2]])
C = np.multiply(A,B)
print('값',C,", 형태",C.shape)

값 [[ -1   0  15]
 [ 10  24 -16]] , 형태 (2, 3)


- 텐서 조작
 1. 재배열 (스칼라=>벡터, 벡터=>행렬 등등 랭크를 높이는 행위)
 2. 텐서 합치기

In [ ]:
#재배열 numpy => reshape , torch => view
a= np.array(30)
print("형태",a.shape) #()
a_new = a.reshape(-1,1) # -1*1 행렬, 숫자가 하나 뿐이므로 -1은 1로 치환됨
print("형태",a_new.shape)

vec1 = np.linspace(-1,1,100) #100의 벡터
print('형태',vec1.shape)
#(100,) => (5,20)
mat1_vec_1 = vec1.reshape(-1,20)  # 5 X 20 = 100이므로 -1이 5로 치환됨
print('바뀐형태', mat1_vec_1.shape)

# 행렬 재배열 Transpose 즉 전치행렬
a = np.random.normal(size=(3,5))
b = a.T 
print('a 형태',a.shape)
print('a.T 형태',b.shape)

형태 ()
형태 (1, 1)
형태 (100,)
바뀐형태 (5, 20)
a 형태 (3, 5)
a.T 형태 (5, 3)


In [ ]:
vec1 = np.array([1,2,3])
vec2 = np.array([2,4,5])
vec3 = np.array([3,6,10])

# 백터의 연결 
#1번째 3+3+3 (9,)
con1 = np.concatenate((vec1,vec2,vec3))
print('9차원 벡터 결과',con1.shape)
#2번째 (3,1),(3,1),(3,1) (3,3)
con2 = np.concatenate((vec1.reshape(-1,1),vec2.reshape(-1,1),vec3.reshape(-1,1)),axis=1) #더해야할 차원의 옵션 즉 (3,1)에서 1을 더하기 위해 두번째(=1) 차원을 더함
print('3*3차원 벡터 결과',con2.shape)

9차원 벡터 결과 (9,)
3*3차원 벡터 결과 (3, 3)


In [ ]:
#과제2
vec1 = np.array([1,2,3]).reshape(-1,1)
vec2 = np.array([2,4,5]).reshape(-1,1)
vec3 = np.array([3,6,10]).reshape(-1,1)
con3 = np.concatenate((vec1,vec2,vec3),axis=1)
print(con3.shape)

(3, 3)
